font-family = "DepartureMono Nerd Font"
font-style = normal
font-style-bold = bold
font-style-italic = italic
font-style-bold-italic = bold-italic
font-synthetic-style = false
font-size = 12
grapheme-width-method = unicode

theme = /home/laeeq/.config/ghostty/themes/aurora-custom.ghostty.bak

background-opacity = 0.92


cursor-style = bar
mouse-hide-while-typing = true

window-padding-x = 16
window-padding-y = 8
window-decoration = none
window-inherit-working-directory = true
window-inherit-font-size = true
window-colorspace = srgb
window-new-tab-position = current

focus-follows-mouse = true
